name: Process Domain Lists

on:
  push:
    branches:
      - master  # 替换为你的实际分支名称
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时触发一次

jobs:
  process_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Download and Process Domain Lists
      run: |
        #!/bin/bash

        # Define the URLs
        urls=(
          "https://raw.githubusercontent.com/Cats-Team/AdRules/script/script/allowlist.txt"
          "https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-list.txt"
          # Add other URLs here if needed
        )

        # Temporary file to hold all domains
        temp_file="all_domains.txt"
        filtered_file="filtered_domains.txt"

        # Step 1: Download, filter, and merge domain lists
        for url in "${urls[@]}"; do
          curl -s "$url" | awk 'NF && !/^#|^!/' >> "$temp_file"
        done

        # Step 2: Save raw domains to filtered_domains.txt
        cp "$temp_file" "$filtered_file"

        # Step 3: Create allow.txt with @@||...^ format from the filtered file
        awk '{ print "@@||" $0 "^" }' "$filtered_file" > allow.txt

        # Step 4: Remove duplicates and sort the domains, then filter out regex patterns for pure_domains.txt
        sort -u "$filtered_file" | grep -Ev '^[.*\\\*\?\+\[\]\(\)\{\}\^\$\|]+.*$' > pure_domains.txt

        # Create the target directory if it does not exist
        mkdir -p data/rules

        # Move the generated files to the processed folder
        mv allow.txt data/rules/
        mv pure_domains.txt data/rules/

    - name: Git push assets to GitHub
      run: |
        # Initialize git repository and set user details
        git init
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check for changes and commit if necessary
        git add data/rules/allow.txt data/rules/pure_domains.txt
        git diff --cached --quiet || git commit -m "Updated at $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')（北京时间）"
        
        # Push changes
        git branch -M master
        git remote add origin https://github.com/greatcoolge/HyperADRules.git
        git push -u origin master --force
