name: Process Domain Lists

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  process_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Download and Process Domain Lists
      run: |
        #!/bin/bash

        # Define the URLs
        urls=(
          "https://raw.githubusercontent.com/Cats-Team/AdRules/script/script/allowlist.txt"
          "https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-list.txt"
          # Add other URLs here if needed
        )

        # Temporary file to hold all domains
        temp_file="all_domains.txt"
        filtered_file="filtered_domains.txt"

        # Step 1: Download, filter, and merge domain lists
        for url in "${urls[@]}"; do
          curl -s "$url" | awk 'NF && !/^#|^!/' >> "$temp_file"
        done

        # Step 2: Save raw domains to filtered_domains.txt
        cp "$temp_file" "$filtered_file"

        # Step 3: Create allow.txt with @@||...^ format from the filtered file
        awk '{ print "@@||" $0 "^" }' "$filtered_file" > allow.txt

        # Create the target directory if it does not exist
        mkdir -p data/rules

        # Move the generated file to the processed folder
        mv allow.txt data/rules/

    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git pull origin master

    - name: Commit and Push Changes
      uses: EndBug/add-and-commit@v9
      with:
        add: |
          data/rules/allow.txt
        message: "Updated allow.txt"
        force: true
